//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommitteePayments
    {
        public int ID { get; set; }
        public int Apartment { get; set; }
        public string PaymentFor { get; set; }
        public int SumPayment { get; set; }
        public Nullable<int> NumberOfPayments { get; set; }
    }
}
