//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HomeownerAssociationEntities : DbContext
    {
        public HomeownerAssociationEntities()
            : base("name=HomeownerAssociationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BulletinBoard> BulletinBoard { get; set; }
        public virtual DbSet<CommitteePayments> CommitteePayments { get; set; }
        public virtual DbSet<Expenses> Expenses { get; set; }
        public virtual DbSet<Landlord> Landlord { get; set; }
        public virtual DbSet<Malfunction> Malfunction { get; set; }
        public virtual DbSet<Tenants> Tenants { get; set; }
        public virtual DbSet<Malfunctions> Malfunctions { get; set; }
        public virtual DbSet<PaymentMethods> PaymentMethods { get; set; }
    }
}
