//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public int ID { get; set; }
        public string Category { get; set; }
        public string Professional { get; set; }
        public int SumExpenses { get; set; }
        public Nullable<System.DateTime> DataExpenses { get; set; }
        public string PaymentMethods { get; set; }
    }
}
